import { defineStore } from "pinia";
import { computed, reactive } from "vue";

export const useTeacherStore = defineStore("teacherStore", () => {
  const state = reactive({
    list: [
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
      {
        id: 1,
        firstName: "Dimitres",
        lastName: "Viga",
        login: "user",
        password: "1234",
        info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vel repudiandae accusamus illo architecto repellendus.",
        image: "ABV8520.jpg",
        dateOfBirth: new Date().toJSON(),
        subjectName: "Mathematics",
      },
    ],
  });

  const setList = (list) => {
    state.list = list;
  };

  const addItem = (item) => {
    state.list.push(item);
  };

  const getList = computed(() => state.list);

  return { setList, addItem, getList };
});
