import { defineStore } from "pinia";
import { computed, reactive } from "vue";

export const useStudentStore = defineStore("studentStore", () => {
  const state = reactive({
    list: [
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
      {
        id: 1,
        firstName: "Dimitres ",
        lastName: "Viga",
        dateOfBirth: new Date().toJSON(),
        groupId: "user",
        login: "user",
        password: "1234",
        image: "ABV8520.jpg",
      },
    ],
  });

  const setList = (list) => {
    state.list = list;
  };

  const addItem = (item) => {
    state.list.push(item);
  };

  const getList = computed(() => state.list);

  return { setList, addItem, getList };
});
